
  
  const currencies = [
    { label: "AED", value: "AED", name: "UAE Dirham", country: "United Arab Emirates" },
    { label: "AFN", value: "AFN", name: "Afghan Afghani", country: "Afghanistan" },
    { label: "ALL", value: "ALL", name: "Albanian Lek", country: "Albania" },
    { label: "AMD", value: "AMD", name: "Armenian Dram", country: "Armenia" },
    { label: "ANG", value: "ANG", name: "Netherlands Antillian Guilder", country: "Netherlands Antilles" },
    { label: "AOA", value: "AOA", name: "Angolan Kwanza", country: "Angola" },
    { label: "ARS", value: "ARS", name: "Argentine Peso", country: "Argentina" },
    { label: "AUD", value: "AUD", name: "Australian Dollar", country: "Australia" },
    { label: "AWG", value: "AWG", name: "Aruban Florin", country: "Aruba" },
    { label: "AZN", value: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan" },
    { label: "BAM", value: "BAM", name: "Bosnia and Herzegovina Mark", country: "Bosnia and Herzegovina" },
    { label: "BBD", value: "BBD", name: "Barbados Dollar", country: "Barbados" },
    { label: "BDT", value: "BDT", name: "Bangladeshi Taka", country: "Bangladesh" },
    { label: "BGN", value: "BGN", name: "Bulgarian Lev", country: "Bulgaria" },
    { label: "BHD", value: "BHD", name: "Bahraini Dinar", country: "Bahrain" },
    { label: "BIF", value: "BIF", name: "Burundian Franc", country: "Burundi" },
    { label: "BMD", value: "BMD", name: "Bermudian Dollar", country: "Bermuda" },
    { label: "BND", value: "BND", name: "Brunei Dollar", country: "Brunei" },
    { label: "BOB", value: "BOB", name: "Bolivian Boliviano", country: "Bolivia" },
    { label: "BRL", value: "BRL", name: "Brazilian Real", country: "Brazil" },
    { label: "BSD", value: "BSD", name: "Bahamian Dollar", country: "Bahamas" },
    { label: "BTN", value: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan" },
    { label: "BWP", value: "BWP", name: "Botswana Pula", country: "Botswana" },
    { label: "BYN", value: "BYN", name: "Belarusian Ruble", country: "Belarus" },
    { label: "BZD", value: "BZD", name: "Belize Dollar", country: "Belize" },
    { label: "CAD", value: "CAD", name: "Canadian Dollar", country: "Canada" },
    { label: "CDF", value: "CDF", name: "Congolese Franc", country: "Democratic Republic of the Congo" },
    { label: "CHF", value: "CHF", name: "Swiss Franc", country: "Switzerland" },
    { label: "CLP", value: "CLP", name: "Chilean Peso", country: "Chile" },
    { label: "CNY", value: "CNY", name: "Chinese Renminbi", country: "China" },
    { label: "COP", value: "COP", name: "Colombian Peso", country: "Colombia" },
    { label: "CRC", value: "CRC", name: "Costa Rican Colon", country: "Costa Rica" },
    { label: "CUP", value: "CUP", name: "Cuban Peso", country: "Cuba" },
    { label: "CVE", value: "CVE", name: "Cape Verdean Escudo", country: "Cape Verde" },
    { label: "CZK", value: "CZK", name: "Czech Koruna", country: "Czech Republic" },
    { label: "DJF", value: "DJF", name: "Djiboutian Franc", country: "Djibouti" },
    { label: "DKK", value: "DKK", name: "Danish Krone", country: "Denmark" },
    { label: "DOP", value: "DOP", name: "Dominican Peso", country: "Dominican Republic" },
    { label: "DZD", value: "DZD", name: "Algerian Dinar", country: "Algeria" },
    { label: "EGP", value: "EGP", name: "Egyptian Pound", country: "Egypt" },
    { label: "ERN", value: "ERN", name: "Eritrean Nakfa", country: "Eritrea" },
    { label: "ETB", value: "ETB", name: "Ethiopian Birr", country: "Ethiopia" },
    { label: "EUR", value: "EUR", name: "Euro", country: "European Union" },
    { label: "FJD", value: "FJD", name: "Fiji Dollar", country: "Fiji" },
    { label: "GBP", value: "GBP", name: "Pound Sterling", country: "United Kingdom" },
    { label: "GEL", value: "GEL", name: "Georgian Lari", country: "Georgia" },
    { label: "GHS", value: "GHS", name: "Ghanaian Cedi", country: "Ghana" },
    { label: "GIP", value: "GIP", name: "Gibraltar Pound", country: "Gibraltar" },
    { label: "GNF", value: "GNF", name: "Guinean Franc", country: "Guinea" },
    { label: "GTQ", value: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala" },
    { label: "GYD", value: "GYD", name: "Guyanese Dollar", country: "Guyana" },
    { label: "HKD", value: "HKD", name: "Hong Kong Dollar", country: "Hong Kong" },
    { label: "HNL", value: "HNL", name: "Honduran Lempira", country: "Honduras" },
    { label: "HRK", value: "HRK", name: "Croatian Kuna", country: "Croatia" },
    { label: "HTG", value: "HTG", name: "Haitian Gourde", country: "Haiti" },
    { label: "HUF", value: "HUF", name: "Hungarian Forint", country: "Hungary" },
    { label: "IDR", value: "IDR", name: "Indonesian Rupiah", country: "Indonesia" },
    { label: "ILS", value: "ILS", name: "Israeli New Shekel", country: "Israel" },
    { label: "INR", value: "INR", name: "Indian Rupee", country: "India" },
    { label: "IQD", value: "IQD", name: "Iraqi Dinar", country: "Iraq" },
    { label: "IRR", value: "IRR", name: "Iranian Rial", country: "Iran" },
    { label: "ISK", value: "ISK", name: "Icelandic Króna", country: "Iceland" },
    { label: "JPY", value: "JPY", name: "Japanese Yen", country: "Japan" },
    { label: "KES", value: "KES", name: "Kenyan Shilling", country: "Kenya" },
    { label: "KGS", value: "KGS", name: "Kyrgyzstani Som", country: "Kyrgyzstan" },
    { label: "KHR", value: "KHR", name: "Cambodian Riel", country: "Cambodia" },
    { label: "KRW", value: "KRW", name: "South Korean Won", country: "South Korea" },
    { label: "KWD", value: "KWD", name: "Kuwaiti Dinar", country: "Kuwait" },
    { label: "KZT", value: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan" },
    { label: "LAK", value: "LAK", name: "Lao Kip", country: "Laos" },
    { label: "LBP", value: "LBP", name: "Lebanese Pound", country: "Lebanon" },
    { label: "LKR", value: "LKR", name: "Sri Lanka Rupee", country: "Sri Lanka" },
    { label: "LRD", value: "LRD", name: "Liberian Dollar", country: "Liberia" },
    { label: "LSL", value: "LSL", name: "Lesotho Loti", country: "Lesotho" },
    { label: "LYD", value: "LYD", name: "Libyan Dinar", country: "Libya" },
    { label: "MAD", value: "MAD", name: "Moroccan Dirham", country: "Morocco" },
    { label: "MDL", value: "MDL", name: "Moldovan Leu", country: "Moldova" },
    { label: "MGA", value: "MGA", name: "Malagasy Ariary", country: "Madagascar" },
    { label: "MKD", value: "MKD", name: "Macedonian Denar", country: "North Macedonia" },
    { label: "MMK", value: "MMK", name: "Burmese Kyat", country: "Myanmar" },
    { label: "MNT", value: "MNT", name: "Mongolian Tögrög", country: "Mongolia" },
    { label: "MOP", value: "MOP", name: "Macanese Pataca", country: "Macau" },
    { label: "MRU", value: "MRU", name: "Mauritanian Ouguiya", country: "Mauritania" },
    { label: "MUR", value: "MUR", name: "Mauritian Rupee", country: "Mauritius" },
    { label: "MWK", value: "MWK", name: "Malawian Kwacha", country: "Malawi" },
    { label: "MXN", value: "MXN", name: "Mexican Peso", country: "Mexico" },
    { label: "MYR", value: "MYR", name: "Malaysian Ringgit", country: "Malaysia" },
    { label: "MZN", value: "MZN", name: "Mozambican Metical", country: "Mozambique" },
    { label: "NAD", value: "NAD", name: "Namibian Dollar", country: "Namibia" },
    { label: "NGN", value: "NGN", name: "Nigerian Naira", country: "Nigeria" },
    { label: "NIO", value: "NIO", name: "Nicaraguan Córdoba", country: "Nicaragua" },
    { label: "NOK", value: "NOK", name: "Norwegian Krone", country: "Norway" },
    { label: "NPR", value: "NPR", name: "Nepalese Rupee", country: "Nepal" },
    { label: "NZD", value: "NZD", name: "New Zealand Dollar", country: "New Zealand" },
    { label: "OMR", value: "OMR", name: "Omani Rial", country: "Oman" },
    { label: "PAB", value: "PAB", name: "Panamanian Balboa", country: "Panama" },
    { label: "PEN", value: "PEN", name: "Peruvian Sol", country: "Peru" },
    { label: "PHP", value: "PHP", name: "Philippine Peso", country: "Philippines" },
    { label: "PKR", value: "PKR", name: "Pakistani Rupee", country: "Pakistan" },
    { label: "PLN", value: "PLN", name: "Polish Złoty", country: "Poland" },
    { label: "PYG", value: "PYG", name: "Paraguayan Guaraní", country: "Paraguay" },
    { label: "QAR", value: "QAR", name: "Qatari Riyal", country: "Qatar" },
    { label: "RON", value: "RON", name: "Romanian Leu", country: "Romania" },
    { label: "RUB", value: "RUB", name: "Russian Ruble", country: "Russia" },
    { label: "RWF", value: "RWF", name: "Rwandan Franc", country: "Rwanda" },
    { label: "SAR", value: "SAR", name: "Saudi Riyal", country: "Saudi Arabia" },
    { label: "SBD", value: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands" },
    { label: "SCR", value: "SCR", name: "Seychellois Rupee", country: "Seychelles" },
    { label: "SDG", value: "SDG", name: "Sudanese Pound", country: "Sudan" },
    { label: "SEK", value: "SEK", name: "Swedish Krona", country: "Sweden" },
    { label: "SGD", value: "SGD", name: "Singapore Dollar", country: "Singapore" },
    { label: "THB", value: "THB", name: "Thai Baht", country: "Thailand" },
    { label: "TJS", value: "TJS", name: "Tajikistani Somoni", country: "Tajikistan" },
    { label: "TMT", value: "TMT", name: "Turkmenistani Manat", country: "Turkmenistan" },
    { label: "TND", value: "TND", name: "Tunisian Dinar", country: "Tunisia" },
    { label: "TOP", value: "TOP", name: "Tongan Paʻanga", country: "Tonga" },
    { label: "TRY", value: "TRY", name: "Turkish Lira", country: "Turkey" },
    { label: "TTD", value: "TTD", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago" },
    { label: "TWD", value: "TWD", name: "New Taiwan Dollar", country: "Taiwan" },
    { label: "TZS", value: "TZS", name: "Tanzanian Shilling", country: "Tanzania" },
    { label: "UAH", value: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine" },
    { label: "UGX", value: "UGX", name: "Ugandan Shilling", country: "Uganda" },
    { label: "USD", value: "USD", name: "United States Dollar", country: "United States" },
    { label: "UYU", value: "UYU", name: "Uruguayan Peso", country: "Uruguay" },
    { label: "UZS", value: "UZS", name: "Uzbekistani Som", country: "Uzbekistan" },
    { label: "VEF", value: "VEF", name: "Venezuelan Bolívar", country: "Venezuela" },
    { label: "VND", value: "VND", name: "Vietnamese Đồng", country: "Vietnam" },
    { label: "VUV", value: "VUV", name: "Vanuatu Vatu", country: "Vanuatu" },
    { label: "WST", value: "WST", name: "Samoan Tala", country: "Samoa" },
    { label: "XAF", value: "XAF", name: "Central African CFA Franc", country: "Central African CFA countries" },
    { label: "XCD", value: "XCD", name: "East Caribbean Dollar", country: "East Caribbean states" },
    { label: "XOF", value: "XOF", name: "West African CFA Franc", country: "West African CFA countries" },
    { label: "YER", value: "YER", name: "Yemeni Rial", country: "Yemen" },
    { label: "ZAR", value: "ZAR", name: "South African Rand", country: "South Africa" },
    { label: "ZMW", value: "ZMW", name: "Zambian Kwacha", country: "Zambia" },
    { label: "ZWL", value: "ZWL", name: "Zimbabwean Dollar", country: "Zimbabwe" }
  ];
  
  export { currencies };
  